version: '3'
services:
  redis-cache:
    container_name: "redis-cache"
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - redis-cluster-starter
    networks:
      app_subnet:
        ipv4_address: 172.20.0.37
  redis-cluster-starter:
    container_name: "redis-cluster-starter"
    image: redis:7.0-alpine
    command: redis-cli --cluster create 172.20.0.31:7001 172.20.0.32:7002 172.20.0.33:7003 172.20.0.34:7004 172.20.0.35:7005 172.20.0.36:7006 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
    networks:
      app_subnet:
        ipv4_address: 172.20.0.30
  redis-node1:
    container_name: "redis-node1"
    image: redis:7.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '7001:7001'
      - '17001:17001'
    volumes:
      - ./node1.conf:/usr/local/etc/redis/redis.conf
    networks:
      app_subnet:
        ipv4_address: 172.20.0.31
  redis-node2:
    container_name: "redis-node2"
    image: redis:7.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '7002:7002'
      - '17002:17002'
    volumes:
      - ./node2.conf:/usr/local/etc/redis/redis.conf
    networks:
      app_subnet:
        ipv4_address: 172.20.0.32
  redis-node3:
    container_name: "redis-node3"
    image: redis:7.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '7003:7003'
      - '17003:17003'
    volumes:
      - ./node3.conf:/usr/local/etc/redis/redis.conf
    networks:
      app_subnet:
        ipv4_address: 172.20.0.33
  redis-node4:
    container_name: "redis-node4"
    image: redis:7.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '7004:7004'
      - '17004:17004'
    volumes:
      - ./node4.conf:/usr/local/etc/redis/redis.conf
    networks:
      app_subnet:
        ipv4_address: 172.20.0.34
  redis-node5:
    container_name: "redis-node5"
    image: redis:7.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '7005:7005'
      - '17005:17005'
    volumes:
      - ./node5.conf:/usr/local/etc/redis/redis.conf
    networks:
      app_subnet:
        ipv4_address: 172.20.0.35
  redis-node6:
    container_name: "redis-node6"
    image: redis:7.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '7006:7006'
      - '17006:17006'
    volumes:
      - ./node6.conf:/usr/local/etc/redis/redis.conf
    networks:
      app_subnet:
        ipv4_address: 172.20.0.36
networks:
  app_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
